export const userTypes = [
  { id: 1, label: "main_admin", name: "Admin" },
  { id: 2, label: "user", name: "User" },
  { id: 3, label: "desc_user", name: "DESC User" },
];

export const adminTypes = [
  { id: 1, name: "Main Admin", value: "main_admin" },
  { id: 1, name: "DESC Admin", value: "desc_admin" },
];

export const skillMaximumScoreValue = 3;

export const mainCategory = [
  { id: 1, name: "Data Analytics", value: "data_analytics" },
  { id: 2, name: "Cyber Security", value: "cyber_security" },
  { id: 3, name: "ICT", value: "ict" },
];
export const mainEntity = [
  { id: 1, label: "DEWA", value: "dewa", logo: "dewa.jpeg" },
  {
    id: 2,
    label: "Dubai Municipality",
    value: "dubai_municipality",
    logo: "dubai-municipality.jpeg",
  },
  { id: 3, label: "Dubai DET", value: "dubai_det", logo: "det.png" },

  {
    id: 4,
    label: "Department of finance dubai",
    value: "dept_of_finance_dubai",
    logo: "dof.jpeg",
  },
  {
    id: 5,
    label: "Dubai digital authority",
    value: "dept_of_finance_dubai",
    logo: "digital-dubai.png",
  },
  {
    id: 7,
    label: "Department of Economic Development",
    value: "dept_of_economic_development",
    logo: "ded.jpeg",
  },
  {
    id: 8,
    label: "Dubai Chamber",
    value: "dubai_chamber",
    logo: "dubai-chamber.png",
  },
  {
    id: 9,
    label: "Dubai customs",
    value: "dubai_customs",
    logo: "dubai-customs.png",
  },
  {
    id: 10,
    label: "Duai Police",
    value: "dubai_police",
    logo: "dubai-police.png",
  },
  {
    id: 11,
    label: "Community Development Authority",
    value: "community_dev_authority",
    logo: "cda.png",
  },
  {
    id: 12,
    label: "DEWA",
    value: "community_dev_authority",
    logo: "dewa.jpeg",
  },
  {
    id: 13,
    label: "UAE University",
    value: "uae university",
    logo: "uaeu.png",
  },
];

export const chartDetails = {
  data_analytics: {
    id: 1,
    name: "Data Analytics",
    value: "data_analytics",
    total_employees: 40,
  },
  cyber_security: {
    id: 2,
    name: "Cyber Security",
    value: "cyber_security",
    total_employees: 86,
  },
  ict: { id: 3, name: "ICT", value: "ict", total_employees: 58 },
};

export const countryList = [
  { label: "United States", value: "US" },
  { label: "China", value: "CN" },
  { label: "India", value: "IN" },
  { label: "United Kingdom", value: "GB" },
  { label: "Russia", value: "RU" },
  { label: "Germany", value: "DE" },
  { label: "France", value: "FR" },
  { label: "Japan", value: "JP" },
  { label: "Brazil", value: "BR" },
  { label: "Canada", value: "CA" },
  { label: "Italy", value: "IT" },
  { label: "South Korea", value: "KR" },
  { label: "Australia", value: "AU" },
  { label: "Spain", value: "ES" },
  { label: "Mexico", value: "MX" },
  { label: "Indonesia", value: "ID" },
  { label: "Netherlands", value: "NL" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "Turkey", value: "TR" },
  { label: "Switzerland", value: "CH" },
  { label: "Sweden", value: "SE" },
  { label: "Poland", value: "PL" },
  { label: "Belgium", value: "BE" },
  { label: "Norway", value: "NO" },
  { label: "Ukraine", value: "UA" },
  { label: "Denmark", value: "DK" },
  { label: "Singapore", value: "SG" },
  { label: "Malaysia", value: "MY" },
  { label: "Egypt", value: "EG" },
  { label: "Philippines", value: "PH" },
  { label: "Vietnam", value: "VN" },
  { label: "Argentina", value: "AR" },
  { label: "Finland", value: "FI" },
  { label: "South Africa", value: "ZA" },
  { label: "Greece", value: "GR" },
  { label: "Colombia", value: "CO" },
  { label: "Ireland", value: "IE" },
  { label: "Iran", value: "IR" },
  { label: "Portugal", value: "PT" },
  { label: "Israel", value: "IL" },
  { label: "Pakistan", value: "PK" },
  { label: "Thailand", value: "TH" },
  { label: "Bangladesh", value: "BD" },
  { label: "Nigeria", value: "NG" },
  { label: "Iraq", value: "IQ" },
  { label: "Chile", value: "CL" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "Morocco", value: "MA" },
  { label: "Peru", value: "PE" },
  { label: "Czech Republic", value: "CZ" },
  { label: "Romania", value: "RO" },
  { label: "Netherlands", value: "NL" },
  { label: "Kazakhstan", value: "KZ" },
  { label: "Belarus", value: "BY" },
  { label: "Sweden", value: "SE" },
  { label: "Ecuador", value: "EC" },
  { label: "United Arab Emirates", value: "AE" },
  { label: "Portugal", value: "PT" },
  { label: "Hungary", value: "HU" },
  { label: "Austria", value: "AT" },
  { label: "Switzerland", value: "CH" },
  { label: "Bolivia", value: "BO" },
  { label: "Qatar", value: "QA" },
  { label: "Dominican Republic", value: "DO" },
  { label: "Costa Rica", value: "CR" },
  { label: "Slovakia", value: "SK" },
  { label: "Tanzania", value: "TZ" },
  { label: "Kuwait", value: "KW" },
  { label: "Uruguay", value: "UY" },
  { label: "Syria", value: "SY" },
  { label: "Lebanon", value: "LB" },
  { label: "Oman", value: "OM" },
  { label: "Panama", value: "PA" },
  { label: "Libya", value: "LY" },
  { label: "Jordan", value: "JO" },
  { label: "Bulgaria", value: "BG" },
  { label: "Guatemala", value: "GT" },
  { label: "Latvia", value: "LV" },
  { label: "Paraguay", value: "PY" },
  { label: "Kenya", value: "KE" },
  { label: "Croatia", value: "HR" },
  { label: "Uzbekistan", value: "UZ" },
  { label: "El Salvador", value: "SV" },
  { label: "Sri Lanka", value: "LK" },
  { label: "Bahrain", value: "BH" },
  { label: "Estonia", value: "EE" },
  { label: "Nepal", value: "NP" },
  { label: "Ethiopia", value: "ET" },
  { label: "Montenegro", value: "ME" },
  { label: "Cyprus", value: "CY" },
  { label: "Zimbabwe", value: "ZW" },
];
